### ISSUE TITLE
Setting up NEC SMDR Collector for NEC SV9500

### ISSUE THREAD

**Issue by DonovanDiamond** [zombat/NEC-SMDR-Collector#1]
I have a NEC SV9500 phone system with around 600 extensions. We have phone codes setup and we need to pull SMDR data from it and store in a database so we can keep track of how much certain people are calling.

I have been searching around and found your project.

I played around with the code a little bit although I am not the most experienced with SMDR pulling. (I mainly deal in programming C# applications and database management.)

The issue I am having is that it will connect and as soon as it tries to pull any data it will immediately disconnect.

I will be back in 18hr.

**Comment by DonovanDiamond** [comment]
Log:
```
Connecting to sv9500 SMDR device 2 at 10.121.129.13 on port 60010
Client connected
Client connection closed
```

**Comment by zombat** [comment]
This is fairly experimental at the moment, and I've only tested it as device 0 with parity turned off.

**Comment by zombat** [comment]
Had a few code errors from previous commits, but 0-3 appear to work. SMDR is a tricky thing, and PBX programming is outside of the scope of this project. I would suggest that you consult with your vendor, and double check your system data.
